# navbar
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  About: /about/

# site icon
favicon: /assert/avatar.png

# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  headerlink: "ยง"

# comments
comments:
  post: true
  about: true

# article directory sidebar
sidebar: true

# Analytics
## Baidu Analytics
baidu_analytics: Your baidu Analytics ID
## Google Analytics
google_analytics: Your Google Analytics ID

# Comments
## Duoshuo
duoshuo_shortname: Your duoshuo ID
## Disqus
disqus_shortname: Your disqus ID

# Social links
social:
  # email: your@email.com
  # stack-overflow:
  # twitter:
  # facebook:
  github: https://github.com/dust8
  # weibo:
  # zhihu:
  rss: /atom.xml
